# NOTE: Search + Replace example.com with your own Cloudflared domain before enabling
tunnel: reclaim-the-stack
credentials-file: /etc/cloudflared/credentials/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
# For more about ingress rules, see
# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
# Applications would typically look like:
# - hostname: <application>.example.com
#   service: http://<application>-web
ingress:
  - hostname: argocd.vikeria.it
    service: https://argocd-server.argocd.svc
    originRequest:
      noTLSVerify: true
  - hostname: grafana.vikeria.it
    service: http://monitoring-grafana.monitoring.svc
  # This rule matches any traffic which didn't match a previous rule and returns 404:
  - service: http_status:404
