---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAP8xvu6UfftBDv7r5lM9sVz6hYq4rZJGYSBtN7a1zB8NtWIcs7+NIngkiOenUaTLB5OtUg9fzSudxnhRHOQu3n1b1iTp+YoJR1PVXdjL85CDUL9xa8csG5zxts2bqRqF123HPQY48e2wIld35naHW5Dchlj6IBTOWEjCjvCFWBQ7BtfbSnIZ4GlQWMfAYi5RQOfqFVPm9M7Ly7I+C/0SfQ9kVjSo/rnOd6/FZw7zdrbpclrgr7nowbSzvD1iLNEZPbfBZZzN++VA4bOd1PbYRvIdZwZ1xhrLTKexSKOGSDsNhExv1wlp5iNkL9qVP/8JjSeZ7gQnqQAgCyCg257PTxEAafJ7Ou9up8F4kbucLDq1rIq1KAQoV6ECfVl6DZ2h2y8rH/4cAMDxNDtAidR/sE0Mi13N7XuZ+AI6NVXDUnvp8G6tCdeFdyUpa21wVyEtEjo+TFhMvgrM31FZQ9DJcoWvTsPpEQbyHdS5jsHij1ilnwMYzsWeYF+AGmvj4NmTpF/YUPzEtc3ZptxVifiwOAyWDZ2Ldr0Ts5GSogY0d2w5i77BxA4EmkwjwrtOVGrqYe/J8uDhiLs3JoQkbxz3Hsk1IhCEL0OvH9UQg/PI9BNj1w5l8VGykwafractfOU5t5fXbtZwblRvVBbM1CQE52gE4nFRe/95XMy8ZqjATGrS0cRoYGcZMeRCcS1oz/pP5pfKlNyHKkQ4yjTtRbWbPObhuzOrk4DxjO72m1dZBdDMohaKZ7qeDOUF2JNQJqRPNxngUyMaL0G+mLAZcilYwYKyTzYZh6oaOKmkXCeyK3EkER7TZW8y8JVTBukHSLDN1H1qp9zrtgqmE4tautJP7Ga9bnW5Rajr+bkTvWs2BifCsU/67KlYT/axakrEAvmSLozYHXiTNcKRY+XaLXZy/9/Q==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
