image: odoo:latest
deployments:
  web:
    replicas: 1
    memory: 512Mi
    cpu: 250m
    # Put ENV which should only apply to the web deployment here
    env:
      - name: WEB_CONCURRENCY
        value: "2"
      - { name: HOST, value: "odoo" }
      - { name: USER, value: "postgres"}
      - { name: PASSWORD, valueFrom: { secretKeyRef: { name: odoo-app, key: password } } }
    # readinessProbePath: /up # when this path returns 200 the pod will be considered ready
    port: 8069
    command: odoo
resources:
  postgres:
    replicas: 2
    memory: 1Gi
    cpu: 1
    disk: 10Gi
    # Tip: generate configuration based on CPU / RAM settings at https://pgtune.leopard.in.ua/
    config:
      max_connections: "40"
      shared_buffers: 256MB
      effective_cache_size: 768MB
      maintenance_work_mem: 64MB
      checkpoint_completion_target: "0.9"
      wal_buffers: 7864kB
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: 3276kB
      min_wal_size: 1GB
      max_wal_size: 4GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: top
# envFrom:
#   - secretRef:
#       name: odoo # Create a dedicated application secret with k secrets:create odoo
env:
  - { name: HOST, value: "odoo" }
  - { name: USER, value: "postgres"}
  - { name: PASSWORD, valueFrom: { secretKeyRef: { name: odoo-app, key: password } } }
