apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: platform/logging
    repoURL: https://github.com/vikeriaconsulting/reclaim-the-stack.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
