# Creates a Deployment and Service for a web application listening on .Values.web.port.
#
# Example values.yaml:
# image: docker.io/vikeriaconsulting/odoo:latest
# deployments:
#   web:
#     replicas: 1
#     memory: 512Mi
#     cpu: 250m
#     # Put ENV which should only apply to the web deployment here
#     env:
#       - name: WEB_CONCURRENCY
#         value: "2"
#     # readinessProbePath: /up # when this path returns 200 the pod will be considered ready
#     # port: <custom-port> (if you don't want to use port 80)
#     # command: <custom-command> (if you don't want to run bin/rails server)
# envFrom:
#   - secretRef:
#       name: odoo # Create a dedicated application secret with k secrets:create odoo
# env: [] # Put ENV which applies to all deployments here

{{- $port := .Values.deployments.web.port | default 80 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-web
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.deployments.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-web
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: web
    spec:
      containers:
        - name: web
          image: {{ .Values.image }}
          command:
            - sh
            - -c
            - {{ .Values.deployments.web.command | default "bin/rails server" }}
          ports:
            - containerPort: {{ $port }}
          securityContext:
            capabilities:
              add:
              - NET_BIND_SERVICE
          {{- if .Values.deployments.web.readinessProbePath }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployments.web.readinessProbePath }}
              port: {{ $port }}
          {{- end }}
          # NOTE: We avoid putting a limit on CPU since Kubernetes throttling kills performance and CPU averages
          # tends to be low, so we can allow some pods to burst when needed. Adjust as you see fit.
          resources:
            requests:
              memory: {{ .Values.deployments.web.memory }}
              cpu: {{ .Values.deployments.web.cpu }}
            limits:
              memory: {{ .Values.deployments.web.memory }}
          envFrom: {{ .Values.envFrom | toYaml | nindent 12 }}
          env:
            {{- if .Values.env }}
            {{- .Values.env | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.deployments.web.env }}
            {{- .Values.deployments.web.env | toYaml | nindent 12 }}
            {{- end }}
            - name: PORT
              value: "{{ $port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-web
spec:
  type: ClusterIP
  ports:
    - port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}-web
